stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/intermediate_data
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/intermediate_data
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed_data
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed_data
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/rf_clf_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/rf_clf_model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/rf_clf_metrics.json
